const mockData = [
    {
        "id": 1,
        "name": "Wireless Headphones",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 99.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-08-13"
    },
    {
        "id": 2,
        "name": "Bluetooth Speaker",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 49.99,
        "rating": 4,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-10-31"
    },
    {
        "id": 3,
        "name": "Smartphone",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 499.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-09-03"
    },
    {
        "id": 4,
        "name": "Gaming Laptop",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 1299.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-09-17"
    },
    {
        "id": 5,
        "name": "4K TV",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 799.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-08-17"
    },
    {
        "id": 6,
        "name": "Running Shoes",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 59.99,
        "rating": 4.2,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-10-20"
    },
    {
        "id": 7,
        "name": "Basketball Sneakers",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 89.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-15"
    },
    {
        "id": 8,
        "name": "Leather Boots",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 149.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-11-01"
    },
    {
        "id": 9,
        "name": "Flip Flops",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 19.99,
        "rating": 3.8,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-09"
    },
    {
        "id": 10,
        "name": "Hiking Boots",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 119.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-10-13"
    },
    {
        "id": 11,
        "name": "Leather Jacket",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 199.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-09-14"
    },
    {
        "id": 12,
        "name": "Jeans",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 39.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-09-26"
    },
    {
        "id": 13,
        "name": "T-Shirt",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 14.99,
        "rating": 4.1,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-10-06"
    },
    {
        "id": 14,
        "name": "Winter Coat",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 149.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-09"
    },
    {
        "id": 15,
        "name": "Sports Hoodie",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 29.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-21"
    },
    {
        "id": 16,
        "name": "Coffee Maker",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 79.99,
        "rating": 4.2,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-07-28"
    },
    {
        "id": 17,
        "name": "Air Fryer",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 129.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-09-07"
    },
    {
        "id": 18,
        "name": "Blender",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 49.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-09-21"
    },
    {
        "id": 19,
        "name": "Washing Machine",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 599.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-30"
    },
    {
        "id": 20,
        "name": "Vacuum Cleaner",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 199.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-04"
    },
    {
        "id": 21,
        "name": "Fiction Novel",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 9.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-10-19"
    },
    {
        "id": 22,
        "name": "Cookbook",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 19.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-06"
    },
    {
        "id": 23,
        "name": "Science Textbook",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 49.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-15"
    },
    {
        "id": 24,
        "name": "Children's Storybook",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 5.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-16"
    },
    {
        "id": 25,
        "name": "Self-Help Book",
        "category": "Art Supplies",
        "brand": "Brand A",
        "price": 15.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 1,
        "category_id": 2,
        "created_at": "2024-08-29"
    },
    {
        "id": 26,
        "name": "Action Camera",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 299.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-09-23"
    },
    {
        "id": 27,
        "name": "Smartwatch",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 199.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-09-12"
    },
    {
        "id": 28,
        "name": "Digital Camera",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 599.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-10-21"
    },
    {
        "id": 29,
        "name": "Portable Charger",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 29.99,
        "rating": 4.2,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-08-26"
    },
    {
        "id": 30,
        "name": "Wireless Mouse",
        "category": "Electronics",
        "brand": "Brand A",
        "price": 39.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 1,
        "category_id": 1,
        "created_at": "2024-10-30"
    },
    {
        "id": 31,
        "name": "Office Chair",
        "category": "Furniture",
        "brand": "Brand A",
        "price": 199.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image5.jpg",
        "brand_id": 1,
        "category_id": 5,
        "created_at": "2024-07-26"
    },
    {
        "id": 32,
        "name": "Dining Table",
        "category": "Furniture",
        "brand": "Brand A",
        "price": 499.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image5.jpg",
        "brand_id": 1,
        "category_id": 5,
        "created_at": "2024-08-23"
    },
    {
        "id": 33,
        "name": "Sofa Set",
        "category": "Furniture",
        "brand": "Brand A",
        "price": 899.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image5.jpg",
        "brand_id": 1,
        "category_id": 5,
        "created_at": "2024-09-01"
    },
    {
        "id": 34,
        "name": "Bookshelf",
        "category": "Furniture",
        "brand": "Brand B",
        "price": 149.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image5.jpg",
        "brand_id": 2,
        "category_id": 5,
        "created_at": "2024-08-05"
    },
    {
        "id": 35,
        "name": "Bed Frame",
        "category": "Furniture",
        "brand": "Brand B",
        "price": 299.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image5.jpg",
        "brand_id": 2,
        "category_id": 5,
        "created_at": "2024-09-04"
    },
    {
        "id": 36,
        "name": "Pillow",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 19.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-08-20"
    },
    {
        "id": 37,
        "name": "Comforter Set",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 89.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-08-23"
    },
    {
        "id": 38,
        "name": "Bed Sheet Set",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 39.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-08-09"
    },
    {
        "id": 39,
        "name": "Bedside Table",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 149.99,
        "rating": 4.2,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-08-25"
    },
    {
        "id": 40,
        "name": "Wall Art",
        "category": "Home Decor",
        "brand": "Brand B",
        "price": 49.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 2,
        "category_id": 4,
        "created_at": "2024-08-10"
    },
    {
        "id": 41,
        "name": "Decorative Vase",
        "category": "Home Decor",
        "brand": "Brand B",
        "price": 29.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 2,
        "category_id": 4,
        "created_at": "2024-09-18"
    },
    {
        "id": 42,
        "name": "Table Lamp",
        "category": "Home Decor",
        "brand": "Brand B",
        "price": 79.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 2,
        "category_id": 4,
        "created_at": "2024-10-03"
    },
    {
        "id": 43,
        "name": "Throw Blanket",
        "category": "Home Decor",
        "brand": "Brand B",
        "price": 34.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 2,
        "category_id": 4,
        "created_at": "2024-08-01"
    },
    {
        "id": 44,
        "name": "Area Rug",
        "category": "Home Decor",
        "brand": "Brand B",
        "price": 199.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 2,
        "category_id": 4,
        "created_at": "2024-08-28"
    },
    {
        "id": 45,
        "name": "Board Game",
        "category": "Toys",
        "brand": "Brand B",
        "price": 29.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 2,
        "category_id": 3,
        "created_at": "2024-09-24"
    },
    {
        "id": 46,
        "name": "Building Blocks",
        "category": "Toys",
        "brand": "Brand B",
        "price": 39.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 2,
        "category_id": 3,
        "created_at": "2024-10-10"
    },
    {
        "id": 47,
        "name": "Puzzle Set",
        "category": "Toys",
        "brand": "Brand B",
        "price": 19.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 2,
        "category_id": 3,
        "created_at": "2024-09-05"
    },
    {
        "id": 48,
        "name": "Action Figure",
        "category": "Toys",
        "brand": "Brand B",
        "price": 24.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 2,
        "category_id": 3,
        "created_at": "2024-08-28"
    },
    {
        "id": 49,
        "name": "Dollhouse",
        "category": "Toys",
        "brand": "Brand B",
        "price": 149.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 2,
        "category_id": 3,
        "created_at": "2024-08-27"
    },
    {
        "id": 50,
        "name": "Yoga Mat",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 39.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-08-26"
    },
    {
        "id": 51,
        "name": "Dumbbell Set",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 89.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-09-12"
    },
    {
        "id": 52,
        "name": "Treadmill",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 599.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-03"
    },
    {
        "id": 53,
        "name": "Exercise Bike",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 299.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-17"
    },
    {
        "id": 54,
        "name": "Resistance Bands",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 24.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-13"
    },
    {
        "id": 55,
        "name": "Garden Tools Set",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 49.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-09-29"
    },
    {
        "id": 56,
        "name": "Planter Pots",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 19.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-09-16"
    },
    {
        "id": 57,
        "name": "Garden Hose",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 39.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-25"
    },
    {
        "id": 58,
        "name": "Patio Furniture Set",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 499.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-08-12"
    },
    {
        "id": 59,
        "name": "Grill",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 299.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-13"
    },
    {
        "id": 60,
        "name": "Camping Tent",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 199.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-11"
    },
    {
        "id": 61,
        "name": "Cooler",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 69.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-27"
    },
    {
        "id": 62,
        "name": "Hiking Backpack",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 89.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-10-14"
    },
    {
        "id": 63,
        "name": "Fishing Rod",
        "category": "Art Supplies",
        "brand": "Brand B",
        "price": 49.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 2,
        "category_id": 2,
        "created_at": "2024-09-24"
    },
    {
        "id": 64,
        "name": "Fitness Tracker",
        "category": "Electronics",
        "brand": "Brand B",
        "price": 59.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 2,
        "category_id": 1,
        "created_at": "2024-08-26"
    },
    {
        "id": 65,
        "name": "Action Camera Accessories",
        "category": "Electronics",
        "brand": "Brand B",
        "price": 29.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 2,
        "category_id": 1,
        "created_at": "2024-10-04"
    },
    {
        "id": 66,
        "name": "VR Headset",
        "category": "Electronics",
        "brand": "Brand B",
        "price": 299.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 2,
        "category_id": 1,
        "created_at": "2024-09-22"
    },
    {
        "id": 67,
        "name": "Smartwatch",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 199.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-08-03"
    },
    {
        "id": 68,
        "name": "Home Security Camera",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 129.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-10-22"
    },
    {
        "id": 69,
        "name": "Smart Light Bulbs",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 39.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-09-16"
    },
    {
        "id": 70,
        "name": "Smart Thermostat",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 199.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-09-05"
    },
    {
        "id": 71,
        "name": "Digital Photo Frame",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 99.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-10-14"
    },
    {
        "id": 72,
        "name": "Portable Charger",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 29.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-09-08"
    },
    {
        "id": 73,
        "name": "Game Console",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 399.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-10-22"
    },
    {
        "id": 74,
        "name": "Video Game Controller",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 59.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-08-10"
    },
    {
        "id": 75,
        "name": "Gaming Chair",
        "category": "Furniture",
        "brand": "Brand C",
        "price": 249.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image5.jpg",
        "brand_id": 3,
        "category_id": 5,
        "created_at": "2024-09-19"
    },
    {
        "id": 76,
        "name": "Wall Clock",
        "category": "Home Decor",
        "brand": "Brand C",
        "price": 39.99,
        "rating": 4.2,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 3,
        "category_id": 4,
        "created_at": "2024-08-22"
    },
    {
        "id": 77,
        "name": "Candle Set",
        "category": "Home Decor",
        "brand": "Brand C",
        "price": 29.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 3,
        "category_id": 4,
        "created_at": "2024-10-02"
    },
    {
        "id": 78,
        "name": "Throw Pillow",
        "category": "Home Decor",
        "brand": "Brand C",
        "price": 19.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 3,
        "category_id": 4,
        "created_at": "2024-09-26"
    },
    {
        "id": 79,
        "name": "Wall Mirror",
        "category": "Home Decor",
        "brand": "Brand C",
        "price": 149.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 3,
        "category_id": 4,
        "created_at": "2024-11-03"
    },
    {
        "id": 80,
        "name": "Potted Plant",
        "category": "Home Decor",
        "brand": "Brand C",
        "price": 24.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image4.jpeg",
        "brand_id": 3,
        "category_id": 4,
        "created_at": "2024-10-01"
    },
    {
        "id": 81,
        "name": "Skateboard",
        "category": "Toys",
        "brand": "Brand C",
        "price": 49.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 3,
        "category_id": 3,
        "created_at": "2024-09-30"
    },
    {
        "id": 82,
        "name": "Remote Control Car",
        "category": "Toys",
        "brand": "Brand C",
        "price": 79.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 3,
        "category_id": 3,
        "created_at": "2024-09-04"
    },
    {
        "id": 83,
        "name": "Magic Set",
        "category": "Toys",
        "brand": "Brand C",
        "price": 34.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 3,
        "category_id": 3,
        "created_at": "2024-08-06"
    },
    {
        "id": 84,
        "name": "Dinosaur Toy",
        "category": "Toys",
        "brand": "Brand C",
        "price": 14.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 3,
        "category_id": 3,
        "created_at": "2024-10-09"
    },
    {
        "id": 85,
        "name": "Toy Train Set",
        "category": "Toys",
        "brand": "Brand C",
        "price": 59.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 3,
        "category_id": 3,
        "created_at": "2024-08-30"
    },
    {
        "id": 86,
        "name": "Kid's Bicycle",
        "category": "Toys",
        "brand": "Brand C",
        "price": 99.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image3.jpeg",
        "brand_id": 3,
        "category_id": 3,
        "created_at": "2024-10-15"
    },
    {
        "id": 87,
        "name": "Paint Set",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 19.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-09-08"
    },
    {
        "id": 88,
        "name": "Sketchbook",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 12.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-10-01"
    },
    {
        "id": 89,
        "name": "Watercolor Set",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 29.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-09-08"
    },
    {
        "id": 90,
        "name": "Canvas Panel",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 24.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-09-05"
    },
    {
        "id": 91,
        "name": "Easel",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 69.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-08-13"
    },
    {
        "id": 92,
        "name": "Sketching Pencils",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 9.99,
        "rating": 4.2,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-08-27"
    },
    {
        "id": 93,
        "name": "Digital Drawing Tablet",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 199.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-10-19"
    },
    {
        "id": 94,
        "name": "Studio Lighting Kit",
        "category": "Art Supplies",
        "brand": "Brand C",
        "price": 89.99,
        "rating": 4.5,
        "imageUrl": "src/assets/images/image2.jpeg",
        "brand_id": 3,
        "category_id": 2,
        "created_at": "2024-10-16"
    },
    {
        "id": 95,
        "name": "Graphic Design Software",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 299.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-08-31"
    },
    {
        "id": 96,
        "name": "Laptop Stand",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 49.99,
        "rating": 4.3,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-09-18"
    },
    {
        "id": 97,
        "name": "Portable Monitor",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 199.99,
        "rating": 4.4,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-10-15"
    },
    {
        "id": 98,
        "name": "Wireless Mouse",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 29.99,
        "rating": 4.6,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-10-11"
    },
    {
        "id": 99,
        "name": "Smartphone",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 699.99,
        "rating": 4.8,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-09-16"
    },
    {
        "id": 100,
        "name": "4K Monitor",
        "category": "Electronics",
        "brand": "Brand C",
        "price": 399.99,
        "rating": 4.7,
        "imageUrl": "src/assets/images/image1.jpeg",
        "brand_id": 3,
        "category_id": 1,
        "created_at": "2024-08-12"
    }
]

export default mockData


